### ISSUE TITLE
Surplus amount being extracted when repaying full debt using RepayAdapter

### ISSUE THREAD

**Issue by parth-15** [aave/aave-debt-swap#5]
`ParaSwapRepayAdapter` is used to repay the debt of user. It offers the functionality to pay partial debt or full debt to the user. When the user wants to pay the full debt of the asset, it is not possible for the UI to determine the amount of debt the user will have when the transaction is mined due to rebasing nature of debt tokens. Due to this, the UI calls the ParaSwap API with extra amount.

ParaSwap team investigated the transactions and found out that:
* UI query a BUY trade for a certain amount Y and ParaSwap API would give the quoted amount X
* ParaSwap API will build the calldata based on buy(X, Y)
* then onchain, `ParaSwapRepayAdapter` perform extract processing which lead to ending up with a new value Y'(this may be less than Y) 
* `ParaSwapRepayAdapter` call augustus with buy(X, Y')

The last step is where the troubles arise, because Y' < Y, then on executing the actual buy, ParaSwap router would pull out of the user an amount X' < X but as pass the expected amount as X, and this leads to a virtual positive slippage and this is where ParaSwap router would take surplus (buy paradigm: the lower amount user spend the better it’s)

Potential Solution
* While there is no straight solution for the above issue, the impact of the issue can be reduced by ensuring that the difference between amount of debt to be paid(at the time of transaction execution) and the amount quoted for paraswap api is less than certain threshold. 
* Currently, UI assumes that the transaction mining happens within 60 minutes and queries the ParaSwap API with the predicted debt amount after 60 minutes which is too pessimistic assumption. This can be reduced to 30 minutes so that difference of amount is reduced.

**Comment by parth-15** [comment]
@miguelmtzinf

**Comment by miguelmtzinf** [comment]
The integration of these contracts in the UI must use an accurate estimation of the full balance of the user so there is little difference between the amount used for the ParaSwap API call and the ParaSwap Augustus swap. A note about this matter to the Security considerations section of the README was added.
